import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.css';
import { config } from "@fortawesome/fontawesome-svg-core";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
config.autoAddCss = false;

const interTight = Inter_Tight({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Invoice AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interTight.className} antialiased scroll-smooth`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
