import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
config.autoAddCss = false;

const interTight = Inter_Tight({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Invoice AI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`${interTight.className} antialiased scroll-smooth`}>
        <NextIntlClientProvider>
          <Header />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
